name: React CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: cd frontend && npm install

    - name: Run tests
      run: cd frontend && npm test

    - name: Build
      run: cd frontend && npm run build

    # Add additional steps for deployment or other actions
